TokoSumi.WEB/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Toko_Sumi.DATAMODELS;
using Toko_Sumi.REPO;
using Toko_Sumi.VIEWMODELS;
using TokoSumi.WEB.AddOns;
using TokoSumi.WEB.Models;

namespace TokoSumi.WEB.Controllers
{
    public class CategoryController : Controller
    {
        //private static List<CategoryModel> list = new List<CategoryModel>()
        //{
        //    new CategoryModel() {Id = 1,nama_category="Food",description="Category of Food" },
        //    new CategoryModel() {Id = 2,nama_category="Drink",description="Category of Drink" }
        //};

        private readonly Toko_SumiContext db;
        private readonly CategoryRepo Repo;
        public CategoryController(Toko_SumiContext db)
        {
            this.db = db;
            Repo = new CategoryRepo(db);
        }
        public IActionResult Index(string sortOrder, int IdCategory, string searchName, string currentFilter, int? pageNumber)
        {
            ViewBag.nameCategory = String.IsNullOrEmpty(sortOrder) ? "name_cat_desc" : "";
            ViewBag.idCategory = sortOrder == "IdCategory" ? "id_cat_desc" : "IdCategory";
            ViewBag.CurrentSort = sortOrder;

            DateTime dtNow = DateTime.Now;
            ViewBag.Tanggal = dtNow;

            
            if (searchName != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchName = currentFilter;
            }
            ViewBag.nama = searchName;
            List<VMCategory> list = Repo.AllData();

            if (!String.IsNullOrEmpty(searchName))
            {
                list = list.Where(c => c.NameCategory.ToLower().Contains(searchName)).ToList();
                //ViewBag.nama = searchName;
            }
            
            switch (sortOrder)
            {
                case "name_cat_desc":
                    list = list.OrderByDescending(c => c.NameCategory).ToList();
                    break;
                case "id_cat_desc":
                    list = list.OrderByDescending(c => c.IdCategory).ToList();
                    break;
                case "IdCategory":
                    list = list.OrderBy(c => c.IdCategory).ToList();
                    break;
                default:
                    list = list.OrderBy(c => c.NameCategory).ToList();
                    break;
            }
            int pageSize = 3;
            //return View(list);
            return View(PaginatedList<VMCategory>.Create(list, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(VMCategory dataVM)
        {
            dataVM.IsDelete = false;
            dataVM.CreateBy = 1;
            dataVM.CreateDate = DateTime.Now;

            bool respon = Repo.Create(dataVM);

            if (respon)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int IdCategory)
        {
            VMCategory dataVM = Repo.getById(IdCategory);

            return View(dataVM);
        }

        [HttpPost]

        public IActionResult Edit(VMCategory dataVM)
        {
            dataVM.UpdateBy = 1;
            dataVM.UpdateDate = DateTime.Now;

            bool respon = Repo.Edit(dataVM);
            if(respon)
            {
                return RedirectToAction("Index");
            }
            return View(dataVM);


        }

        public IActionResult Detail(int IdCategory)
        {
            VMCategory dataVM = Repo.getById(IdCategory);
            return View(dataVM);
        }

        //public bool Delete(VMCategory dataVM)
        //{

        //}
        [HttpGet]
        public IActionResult Delete(int IdCategory)
        {
            VMCategory dataVM = Repo.getById(IdCategory);
            return View(dataVM);
        }
        [HttpPost]
        public IActionResult Delete(VMCategory dataVM)
        {
            dataVM.UpdateBy = 1;
            dataVM.UpdateDate = DateTime.Now;

            bool respon = Repo.Delete(dataVM);
            if (respon)
            {
                return RedirectToAction("Index");
            }
            return View(dataVM);


        }
    }
}

TokoSumi.WEB/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Toko_Sumi.DATAMODELS;
using Toko_Sumi.REPO;
using Toko_Sumi.VIEWMODELS;
using TokoSumi.WEB.AddOns;
using TokoSumi.WEB.Models;
namespace TokoSumi.WEB.Controllers
{
    public class VariantController : Controller
    {
        private readonly Toko_SumiContext db;
        private readonly VariantRepo Repo;
        private readonly CategoryRepo RepoC;


        public VariantController(Toko_SumiContext db)
        {
            this.db = db;
            Repo = new VariantRepo(db);
            RepoC = new CategoryRepo(db);
        }


        public IActionResult Index(string sortOrder,
                                    int IdVariant,
                                    string searchName,
                                    string currentFilter,
                                    int?pageNumber  )
        {
            ViewBag.nameVariant = string.IsNullOrEmpty(sortOrder) ? "name_var_desc" : "";
            ViewBag.idVariant = sortOrder == "IdVariant" ? "id_var_desc" : "IdVariant";
            ViewBag.CurrentSort = sortOrder;

            DateTime dtNow = DateTime.Now;
            ViewBag.Tanggal = dtNow;

            if(searchName != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchName = currentFilter;
            }
            ViewBag.nama = searchName;
            List<VMVariant> list = Repo.AllData();

            if (!String.IsNullOrEmpty(searchName))
            {
                list = list.Where(v => v.NameVariant.ToLower().Contains(searchName)).ToList();
            }

            switch (sortOrder)
            {
                case "name_var_desc":
                    list = list.OrderByDescending(v => v.NameVariant).ToList();
                    break;
                case "id_var_desc":
                    list = list.OrderByDescending(v => v.IdVariant).ToList();
                    break;
                case "IdVariant":
                    list = list.OrderBy(v => v.IdVariant).ToList();
                    break;
                default:
                    list = list.OrderBy(v => v.NameVariant).ToList();
                    break;
            }

            int pageSize = 3;
            return View(PaginatedList<VMVariant>.Create(list,pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            List<VMCategory> listCategory = RepoC.AllData();
            ViewBag.ListCategory = listCategory;
            return View();
        }

        [HttpPost]
        public IActionResult Create(VMVariant dataVM)
        {
            dataVM.IsDelete = false;
            dataVM.CreateBy = 1;
            dataVM.CreateDate = DateTime.Now;

            bool respon = Repo.Create(dataVM);

            if (respon)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int IdVariant)
        {
            List<VMCategory> listCategory = RepoC.AllData();
            ViewBag.ListCategory = listCategory;
            VMVariant dataVM = Repo.getById(IdVariant);

            return View(dataVM);
        }

        [HttpPost]
        public IActionResult Edit(VMVariant dataVM)
        {
            dataVM.UpdateBy = 1;
            dataVM.UpdateDate = DateTime.Now;

            bool respon = Repo.Edit(dataVM);
            if(respon)
            {
                return RedirectToAction("Index");
            }
            return View(dataVM);
        }

        public IActionResult Detail(int IdVariant)
        {
            VMVariant dataVM = Repo.getById(IdVariant);
            return View(dataVM);

        }

        [HttpGet]
        public IActionResult Delete(int IdVariant)
        {
            VMVariant dataVM = Repo.getById(IdVariant);
            return View(dataVM);
        }
        [HttpPost]
        public IActionResult Delete(VMVariant dataVM)
        {
            dataVM.UpdateBy = 1;
            dataVM.UpdateDate = DateTime.Now;

            bool respon = Repo.Delete(dataVM);
            if(respon)
            {
                return RedirectToAction("Index");
            }
            return View(dataVM);
        }
    }

}

TokoSumi.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TokoSumi.WEB</title>
    <script src="~/Template/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />*@
    <!-- Custom CSS -->

    <link href="~/Template/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/Template/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/Template/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Template/dist/css/style.min.css" rel="stylesheet">
     
</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
        data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
        <!-- ============================================================== -->
    @Html.Partial("_Header")
    @Html.Partial("_Sidebar")
    

    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TokoSumi.WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class = "nav-item">
                            <a class = "nav-link text-dark" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class = "nav-item">
                            <a class = "nav-link text-dark" asp-controller="Variant" asp-action="Index">Variant</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="page-wrapper">
        <div class="container-fluid">
    
                @RenderBody()
        </div>
    </div>
    <footer class="footer text-center text-muted">
                All Rights Reserved by Adminmart. Designed and Developed by <a
                    href="https://wrappixel.com">WrapPixel</a>.
    </footer>
    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TokoSumi.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
@*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)*@
 @*   <script src="~/Template/assets/libs/jquery/dist/jquery.min.js"></script>*@
    <script src="~/Template/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/Template/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/Template/dist/js/app-style-switcher.js"></script>
    <script src="~/Template/dist/js/feather.min.js"></script>
    <script src="~/Template/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/Template/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/Template/dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="~/Template/assets/extra-libs/c3/d3.min.js"></script>
    <script src="~/Template/assets/extra-libs/c3/c3.min.js"></script>
    <script src="~/Template/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/Template/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/Template/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/Template/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/Template/dist/js/pages/dashboards/dashboard1.min.js"></script>
</body>
</html>

<style>
    .img-responsive {
        width: auto;
        height: 180px !important;
    }
    .button{
        background-color: orange;
          border: none;
          color: white;
          padding: 0px 180px;
          text-align: center;
          text-decoration: none;
          font-size: 16px;
    }
</style>